language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction --prefer-dist
  - git config --global user.name "John Doe"
  - git config --global user.email "example@example.com"
  - mkdir -p build/logs

script:
  - vendor/bin/php-cs-fixer fix --dry-run -v
  - phpdbg -qrr vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v